{
  "special_tokens": {
    "think_start": 151667,
    "think_end": 151668
  },
  "quick": {
    "model_name": "Qwen3-0.6B",
    "model_path": "/home/guohurui/workspace/model/Qwen3-0.6B",
    "param": "0.6",
    "tp_size": 1,
    "base_gpu_id": 0,
    "mem_fraction_static": 0.15
  },
  "reference": {
    "model_name": "Qwen3-32B",
    "model_path": "/home/guohurui/workspace/model/Qwen3-32B-FP8",
    "param": "32",
    "tp_size": 2,
    "base_gpu_id": 1,
    "dtype": "bfloat16",
    "trust_remote_code": true,
    "mem_fraction_static": 0.8,
    "max_prefill_tokens": 4096,
    "max_total_tokens": 8192,
    "kv_cache_dtype": "auto",
    "disable_cuda_graph": true,
    "disable_custom_all_reduce": true,
    "skip_server_warmup": true,
    "schedule_conservativeness": 1.5
  },
  "continuation_main": {
    "model_name": "Qwen3-32B",
    "model_path": "/home/guohurui/workspace/model/Qwen3-32B-FP8",
    "param": "32",
    "tp_size": 2,
    "base_gpu_id": 1,
    "mem_fraction_static": 0.90
  },
  "continuation_reference": {
    "model_name": "Qwen3-32B",
    "model_path": "/home/guohurui/workspace/model/Qwen3-32B-FP8",
    "param": "32",
    "tp_size": 1,
    "base_gpu_id": 3,
    "mem_fraction_static": 0.90
  },
  "verify": {
    "model_name": "Qwen2.5-72B-Instruct",
    "model_path": "Qwen/Qwen2.5-72B-Instruct",
    "mem_fraction_static": 0.90,
    "max_new_tokens": 16,
    "tp_size": 4,
    "base_gpu_id": 4
  },
  "router": {
    "router_name": "Qwen3-0.6B+Qwen3-32B",
    "router_path": "/home/guohurui/workspace/R2R_router_collections/Qwen3-0.6B+Qwen3-32B/default_router.pt",
    "override_init_args":{
      "pretrained_model_name": "/home/guohurui/workspace/model/Qwen3-0.6B"
    }
  }
}
